winget install --id Microsoft.PowerToys
winget install --id JannisX11.Blockbench
winget install --id SomePythonThings.WingetUIStore
winget install --id Microsoft.PCManager
winget install --id Notepad++.Notepad++
winget install --id WhatsApp.WhatsApp
winget install --id 7zip.7zip
winget install --id Audacity.Audacity
winget install --id ShareX.ShareX
winget install --id GitHub.GitHubDesktop
winget install --id GIMP.GIMP